// signup //
{
    "Login": "Se connecter"
    "as" : "comme"
    "a" : "une"
    "guest" : "invitée"
    "Unlock" : "Ouvrir"
    "Opportunities" : "Opportunités"
    "Fuel" : "Carburant"
    "Ambitions" : "Ambitions"
    "The" : "La"
    "Ultimate" : "Ultime"
    "Work" : "Travail"
    "Marketplace" : "Marché"
    "Create" : "Créer"
    "account" : "compte"
    "Already" : "Déjà"
    "have" : "avoir"
    "an" : "un"
    "account" : "compte"
    "Login" : "Se connecter"
    "here" : "ici"
    "First" : "D'abord"
    "name" : "nom"
    "Enter" : "Entrer"
    "your" : "ton"
    "first" : "d'abord"
    "name" : "nom"
    "Last" : "Dernière"
    "name" : "nom"
    "Enter" : "Entrer"
    "your" : "ton"
    "last" : "dernière"
    "name" : "nom"
    "Username" : "Nom d'utilisateur"
    "Enter" : "Entrer"
    "username" : "nom d'utilisateur"
    "Email" : "E-mail"
    "id" : "identifiant"
    "Enter" : "Entrer"
    "your" : "ton"
    "email" : "e-mail"
    "id" : "identifiant"
    "Country" : "Pays"
    "Select" : "Sélectionner"
    "Password" : "Mot de passe"
    "Confirm" : "Mot de passe"
    "password" : "mot de passe"
    "I" : "je"
    "hereby" : "par la présente"
    "confirm" : "confirmer"
    "that" : "Cette"
    "I’m" : "Je suis"
    "above" : "au-dessus de"
    "the" : "la"
    "legal" : "légale"
    "age" : "âge"
    "of" : "de"
    "Signup" : "S'inscrire"
    "Supported" : "Prise en charge"
    "by" : "par"
    "the" : "la"
    "Vienna" : "Vienna"
    "Business" : "Entreprise"
    "Agency" : "Agence"
    "A" : "UNE"
    "fund" : "fonds"
    "of" : "de"
    "the" : "la"
    "City " : "Ville"
    "of" : "de"
    "Vienna" : "Vienne"
}